spring.application.name=NoteP

# 1. VER\u00c4\u00b0TABANI BA\u00c4\u009eLANTI AYARLARI (Ak\u00c4\u00b1ll\u00c4\u00b1 Ge\u00c3\u00a7i\u00c5\u009f)
# Render'da DB_URL varsa PostgreSQL'e ba\u00c4\u009flan\u00c4\u00b1r, yoksa yerel bilgisayar\u00c4\u00b1ndaki MySQL'e ba\u00c4\u009flan\u00c4\u00b1r
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/notep_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:mirza6445}

# S\u00c3\u00bcr\u00c3\u00bcc\u00c3\u00bcy\u00c3\u00bc otomatik se\u00c3\u00a7mesi i\u00c3\u00a7in bo\u00c5\u009f b\u00c4\u00b1rak\u00c4\u00b1yoruz (Spring Boot gelen URL'den MySQL mi Postgres mi oldu\u00c4\u009funu anlar)
spring.datasource.driver-class-name=

# 2. JPA / HIBERNATE AYARLARI (Ak\u00c4\u00b1ll\u00c4\u00b1 Ge\u00c3\u00a7i\u00c5\u009f)
# Render'da bir diyalekt belirtilmediyse yerel bilgisayar\u00c4\u00b1n i\u00c3\u00a7in varsay\u00c4\u00b1lan olarak MySQL diyalektini se\u00c3\u00a7er
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. SUNUCU PORTU
server.port=${PORT:8081}

# 4. JWT VE LOGLAMA AYARLARI
jwt.secretSTR=230316056S215M457R154Z262251962517m\u0131rza
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
springdoc.enable-data-rest=false

# Subabase DB password
subabasePassword=6Liuz8c*s%2gPtp

# Supabase Storage (S3 API) Ayarlar\u0131
supabase.s3.endpoint=https://tkubibnxnxpggbfgknky.supabase.co/storage/v1/s3
supabase.s3.region=eu-central-1
supabase.s3.access-key=c69a154ffd2e52d61b654d5837d4a630
supabase.s3.secret-key=e34c44112c55400e2803d65fb7b0c810b015398c8771a7681ab39a21a5ec9f87
supabase.s3.bucket-name=notep-attachments


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB