spring.application.name=NoteP
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
jwt.secretSTR=230316056S215M457R154Z26