spring.application.name=NoteP

# 1. VERİTABANI BAĞLANTI AYARLARI (Akıllı Geçiş)
# Render'da DB_URL varsa PostgreSQL'e bağlanır, yoksa yerel bilgisayarındaki MySQL'e bağlanır
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/notep_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:mirza6445}

# Sürücüyü otomatik seçmesi için boş bırakıyoruz (Spring Boot gelen URL'den MySQL mi Postgres mi olduğunu anlar)
spring.datasource.driver-class-name=

# 2. JPA / HIBERNATE AYARLARI (Akıllı Geçiş)
# Render'da bir diyalekt belirtilmediyse yerel bilgisayarın için varsayılan olarak MySQL diyalektini seçer
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. SUNUCU PORTU
server.port=${PORT:8080}

# 4. JWT VE LOGLAMA AYARLARI
jwt.secretSTR=230316056S215M457R154Z262251962517m\u0131rza
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
springdoc.enable-data-rest=false